/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package alumni_202557201026;

import com.formdev.flatlaf.FlatLightLaf;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author user
 */
public class f_dashboard extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(f_dashboard.class.getName());

    /**
     * Creates new form f_dashboard
     */
    public f_dashboard() {
        initComponents();
        pcontent.add(new p_dashboard());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p_sidebar = new javax.swing.JPanel();
        logoaloomni = new javax.swing.JLabel();
        bdashboard = new javax.swing.JButton();
        bjurusan = new javax.swing.JButton();
        bguru = new javax.swing.JButton();
        bkelas = new javax.swing.JButton();
        bsiswa = new javax.swing.JButton();
        babout = new javax.swing.JButton();
        blogout = new javax.swing.JButton();
        pcenter = new javax.swing.JPanel();
        ptop = new javax.swing.JPanel();
        bclose = new javax.swing.JLabel();
        pmid = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        pcontent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        p_sidebar.setBackground(new java.awt.Color(0, 151, 215));

        logoaloomni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/Aloomni Logo.png"))); // NOI18N

        bdashboard.setBackground(new java.awt.Color(0, 151, 215));
        bdashboard.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        bdashboard.setForeground(new java.awt.Color(255, 255, 255));
        bdashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/Dashboard Icon.png"))); // NOI18N
        bdashboard.setText("DASHBOARD");
        bdashboard.setBorder(null);
        bdashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bdashboard.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bdashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdashboardActionPerformed(evt);
            }
        });

        bjurusan.setBackground(new java.awt.Color(0, 151, 215));
        bjurusan.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        bjurusan.setForeground(new java.awt.Color(255, 255, 255));
        bjurusan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/Jurusan Icon.png"))); // NOI18N
        bjurusan.setText("JURUSAN");
        bjurusan.setBorder(null);
        bjurusan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bjurusan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bjurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bjurusanActionPerformed(evt);
            }
        });

        bguru.setBackground(new java.awt.Color(0, 151, 215));
        bguru.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        bguru.setForeground(new java.awt.Color(255, 255, 255));
        bguru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/Guru Logo.png"))); // NOI18N
        bguru.setText("GURU");
        bguru.setBorder(null);
        bguru.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bguru.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bguruActionPerformed(evt);
            }
        });

        bkelas.setBackground(new java.awt.Color(0, 151, 215));
        bkelas.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        bkelas.setForeground(new java.awt.Color(255, 255, 255));
        bkelas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/Kelas Icon.png"))); // NOI18N
        bkelas.setText("KELAS");
        bkelas.setBorder(null);
        bkelas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bkelas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bkelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkelasActionPerformed(evt);
            }
        });

        bsiswa.setBackground(new java.awt.Color(0, 151, 215));
        bsiswa.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        bsiswa.setForeground(new java.awt.Color(255, 255, 255));
        bsiswa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/Siswa Icon.png"))); // NOI18N
        bsiswa.setText("SISWA");
        bsiswa.setBorder(null);
        bsiswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bsiswa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bsiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsiswaActionPerformed(evt);
            }
        });

        babout.setBackground(new java.awt.Color(0, 151, 215));
        babout.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        babout.setForeground(new java.awt.Color(255, 255, 255));
        babout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/About Icon.png"))); // NOI18N
        babout.setText("ABOUT");
        babout.setBorder(null);
        babout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        babout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        babout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baboutActionPerformed(evt);
            }
        });

        blogout.setBackground(new java.awt.Color(0, 151, 215));
        blogout.setFont(new java.awt.Font("Nirmala UI", 1, 18)); // NOI18N
        blogout.setForeground(new java.awt.Color(255, 255, 255));
        blogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/Log Out Icon.png"))); // NOI18N
        blogout.setText("LOG OUT");
        blogout.setBorder(null);
        blogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        blogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        blogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p_sidebarLayout = new javax.swing.GroupLayout(p_sidebar);
        p_sidebar.setLayout(p_sidebarLayout);
        p_sidebarLayout.setHorizontalGroup(
            p_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_sidebarLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(logoaloomni)
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_sidebarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(babout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsiswa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bkelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bguru, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bjurusan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bdashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)))
        );
        p_sidebarLayout.setVerticalGroup(
            p_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_sidebarLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(logoaloomni)
                .addGap(54, 54, 54)
                .addComponent(bdashboard)
                .addGap(30, 30, 30)
                .addComponent(bjurusan)
                .addGap(27, 27, 27)
                .addComponent(bguru)
                .addGap(27, 27, 27)
                .addComponent(bkelas)
                .addGap(29, 29, 29)
                .addComponent(bsiswa)
                .addGap(29, 29, 29)
                .addComponent(babout)
                .addGap(26, 26, 26)
                .addComponent(blogout)
                .addContainerGap(186, Short.MAX_VALUE))
        );

        jPanel1.add(p_sidebar, java.awt.BorderLayout.LINE_START);

        pcenter.setBackground(new java.awt.Color(255, 255, 255));
        pcenter.setLayout(new java.awt.BorderLayout());

        ptop.setBackground(new java.awt.Color(227, 227, 227));

        bclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/alumni_202557201026/IMG/Cancel Black.png"))); // NOI18N
        bclose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bcloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ptopLayout = new javax.swing.GroupLayout(ptop);
        ptop.setLayout(ptopLayout);
        ptopLayout.setHorizontalGroup(
            ptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ptopLayout.createSequentialGroup()
                .addContainerGap(991, Short.MAX_VALUE)
                .addComponent(bclose)
                .addContainerGap())
        );
        ptopLayout.setVerticalGroup(
            ptopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bclose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        pcenter.add(ptop, java.awt.BorderLayout.PAGE_START);

        pmid.setBackground(new java.awt.Color(255, 255, 255));
        pmid.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(30, 626));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        pmid.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1030, 20));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pmid.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(30, 626));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        pmid.add(jPanel4, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1030, 20));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1030, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pmid.add(jPanel5, java.awt.BorderLayout.PAGE_END);

        pcontent.setBackground(new java.awt.Color(255, 255, 255));
        pcontent.setForeground(new java.awt.Color(255, 255, 255));
        pcontent.setLayout(new java.awt.CardLayout());
        pmid.add(pcontent, java.awt.BorderLayout.CENTER);

        pcenter.add(pmid, java.awt.BorderLayout.CENTER);

        jPanel1.add(pcenter, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bdashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdashboardActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_dashboard());
        pcontent.repaint();
        pcontent.revalidate();
        
    }//GEN-LAST:event_bdashboardActionPerformed

    private void bguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bguruActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_guru());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_bguruActionPerformed

    private void bkelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkelasActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_kelas());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_bkelasActionPerformed

    private void bsiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsiswaActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_siswa());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_bsiswaActionPerformed

    private void bjurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bjurusanActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_jurusan());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_bjurusanActionPerformed

    private void blogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blogoutActionPerformed
        // TODO add your handling code here:
        new f_confir().setVisible(true);
    }//GEN-LAST:event_blogoutActionPerformed

    private void bcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bcloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bcloseMouseClicked

    private void baboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baboutActionPerformed
        // TODO add your handling code here:
        pcontent.removeAll();
        pcontent.add(new p_about());
        pcontent.repaint();
        pcontent.revalidate();
    }//GEN-LAST:event_baboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            UIManager.put("TextComponent.arc", 15);
            UIManager.put("Button.BorderWidth", 10);
            UIManager.put("Component.BorderWidth", 5);
            UIManager.put( "Component.arc", 15 );
            UIManager.put( "Button.arc", 15 );
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (UnsupportedLookAndFeelException unsupportedLookAndFeelException) {
        }
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new f_dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton babout;
    private javax.swing.JLabel bclose;
    private javax.swing.JButton bdashboard;
    private javax.swing.JButton bguru;
    private javax.swing.JButton bjurusan;
    private javax.swing.JButton bkelas;
    private javax.swing.JButton blogout;
    private javax.swing.JButton bsiswa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel logoaloomni;
    private javax.swing.JPanel p_sidebar;
    private javax.swing.JPanel pcenter;
    private javax.swing.JPanel pcontent;
    private javax.swing.JPanel pmid;
    private javax.swing.JPanel ptop;
    // End of variables declaration//GEN-END:variables
}
